using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class formula : MonoBehaviour
{
    [SerializeField] GameObject formulaLayer;                            // ï¿½ï¿½ï¿½ï¿½ ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] Animator anim;                                      // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    static public bool formulaActiveNow = false;                          // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private bool isAnimating = false; // ğŸš€ Ğ±Ğ»Ğ¾ĞºĞ¸Ñ€Ğ¾Ğ²ĞºĞ° Ğ¿Ğ¾Ğ²Ñ‚Ğ¾Ñ€Ğ½Ñ‹Ñ… Ğ½Ğ°Ğ¶Ğ°Ñ‚Ğ¸Ğ¹

    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ "ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½" ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] GameObject tickMilk;
    [SerializeField] GameObject tickSugar;
    [SerializeField] GameObject tickYeast;
    [SerializeField] GameObject tickFlour;
    [SerializeField] GameObject tickButter;
    [SerializeField] GameObject tickSalt;
    [SerializeField] GameObject tickEgg;
    [SerializeField] GameObject tickJam;


    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] GameObject pointer;                                  // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    public static bool foundAllProduct = false;                           // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

    private void Start()
    {
        anim.GetComponent<Animation>();
    }
    void Update()
    {
        if (Move.products[0] && Move.products[1] && Move.products[2] && Move.products[3] && Move.products[4] && Move.products[5] && Move.products[6] && Move.products[8])
        {
            foundAllProduct = true;
            pointer.SetActive(true);

            if (DoughPie.attemptTest == true) 
            {
                pointer.SetActive(false);
            }

        }

        if (Input.GetKeyDown(KeyCode.Q) && !isAnimating &&
            cookDialog.formulaIsIssued && !DoughPie.isStartingTest && !Move.onTaskNow)
        {
            if (formulaActiveNow)
                StartCoroutine(CloseFormula());
            else
                StartCoroutine(OpenFormula());
        }
    }
    private IEnumerator OpenFormula()
    {
        isAnimating = true;
        formulaActiveNow = true;

        // Ğ²ĞºĞ»ÑÑ‡Ğ°ĞµĞ¼ Ğ³Ğ°Ğ»Ğ¾Ñ‡ĞºĞ¸
        if (Move.products[0]) tickMilk.SetActive(true);
        if (Move.products[1]) tickSugar.SetActive(true);
        if (Move.products[2]) tickYeast.SetActive(true);
        if (Move.products[3]) tickFlour.SetActive(true);
        if (Move.products[4]) tickButter.SetActive(true);
        if (Move.products[5]) tickSalt.SetActive(true);
        if (Move.products[6]) tickEgg.SetActive(true);
        if (Move.products[8]) tickJam.SetActive(true);

        formulaLayer.SetActive(true);
        anim.SetBool("useFormula", true);
        anim.SetBool("offFormula", false);

        yield return new WaitForSeconds(0.3f); // Ğ²Ñ€ĞµĞ¼Ñ Ğ°Ğ½Ğ¸Ğ¼Ğ°Ñ†Ğ¸Ğ¸ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ğ¸Ñ

        anim.SetBool("useFormula", false);
        isAnimating = false;
    }

    private IEnumerator CloseFormula()
    {
        isAnimating = true;

        anim.SetBool("useFormula", false);
        anim.SetBool("offFormula", true);

        yield return new WaitForSeconds(0.8f); // Ğ²Ñ€ĞµĞ¼Ñ Ğ°Ğ½Ğ¸Ğ¼Ğ°Ñ†Ğ¸Ğ¸ Ğ·Ğ°ĞºÑ€Ñ‹Ñ‚Ğ¸Ñ

        formulaActiveNow = false;
        formulaLayer.SetActive(false);
        isAnimating = false;
    }
   


}
